variables:
  test_path: "Tests"
  backend_container: "checkin-backend"

stages:
  - restore
  - build
  - test

restore:
  stage: restore
  image: mcr.microsoft.com/dotnet/sdk:6.0
  only: &default_only_backend
    refs:
      - branches
      - tags
      - merge_requests
  script:
    - dotnet restore --packages obj/dependencies
  artifacts:
    paths:
      - "obj"

before_script:
  - 'dotnet restore'

build:
  stage: build
  needs: ["restore"]
  only:
    <<: *default_only_backend
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - "dotnet build -c Release --packages obj/dependencies"
    - "dotnet build -c Debug --packages obj/dependencies"
  artifacts:
    paths:
      - "Api/bin/Release/net6.0/"
      - "Api/bin/Debug/net6.0/"
      - "App/bin/Release/net6.0/"
      - "App/bin/Debug/net6.0/"
      - "Core/bin/Release/net6.0/"
      - "Core/bin/Debug/net6.0/"
      - "Database/bin/Release/net6.0/"
      - "Database/bin/Debug/net6.0/"

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  needs: ["build"]
  only:
    <<: *default_only_backend
  variables:
    test_path: "UnitTests"
  before_script:
    - "cd $test_path"
  script:
    - apt-get install libsaxonb-java
    - dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
    - dotnet test --logger:"nunit;LogFilePath=$CI_PROJECT_DIR/test-result.xml"
    - saxonb-xslt -s $CI_PROJECT_DIR/$TEST_PLATFORM-results.xml -xsl $test_path/ci/nunit-transforms/nunit3-junit.xslt >$test_path/$TEST_PLATFORM-junit-results.xml
  artifacts:
    when: always
    paths:
      - "$test_path/TestResults"
      - "$CI_PROJECT_DIR/test-result.xml"
    reports:
        junit:
          - $CI_PROJECT_DIR/test-result.xml
          - $CI_PROJECT_DIR/$TEST_PLATFORM-coverage/
    expire_in: 2 weeks

#docker:
#  stage: docker
#  tags:
#    - docker
#  needs: ["restore", "build", "test"]
#  only:
#    refs:
#      - branches
#      - tags
#  variables:
#    image_tag_backend:
#      "$CI_REGISTRY/thuas/id-2122-spring/hybrid-check-in-desk/back-end:$CI_COMMIT_REF_SLUG"
#  before_script:
#    - "docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD"
#  script:
#    - "docker build -f Dockerfile -t $image_tag_backend ."
#    - "docker push $image_tag_backend"
#  after_script:
#    - "docker logout registry.gitlab.com"
