image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - test

before_script:
  - 'dotnet restore'

app-build:
  stage: build
  script:
    - 'dotnet build --no-restore'

tests:
    stage: test
    script: 
        - "dotnet test --no-restore"