image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - test

before_script:
  - 'dotnet restore'

app-build:
  stage: build
  script:
    - 'dotnet build --no-restore'

tests:
  stage: test
  script:
    - "dotnet test --no-restore --logger:\"nunit;LogFilePath=$CI_PROJECT_DIR/test-result.xml\""
  artifacts:
    when: always
    reports:
      junit:
        - $CI_PROJECT_DIR/test-result.xml
    expire_in: 2 weeks
