image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - test

before_script:
  - 'dotnet restore'

app-build:
  stage: build
  script:
    - 'dotnet build --no-restore'

tests:
  stage: test
  script:
    # This could be made faster by adding these packages to base image or running in a separate job (and step)
    # We could use an image with these two depencencies only and only do the saxonb-xslt command on
    # previous job's artifacts
    - apt-get update && apt-get install -y default-jre libsaxonb-java
    - "dotnet test --no-restore"
    - saxonb-xslt -s $CI_PROJECT_DIR/$TEST_PLATFORM-results.xml -xsl $CI_PROJECT_DIR/ci/nunit-transforms/nunit3-junit.xslt >$CI_PROJECT_DIR/junit-results.xml
  artifacts:
    when: always
    paths:
    # This is exported to allow viewing the Coverage Report in detail if needed
    - $CI_PROJECT_DIR/coverage/
    reports:
      junit:
        - $CI_PROJECT_DIR/junit-results.xml
        - $CI_PROJECT_DIR/coverage/coverage.xml
    expire_in: 2 weeks
  coverage: /<Linecoverage>(.*?)</Linecoverage>/
